   try{
window.aax = window.aax|| {};
window.aax.isLoaded = true;
var aaxSettings = {"srvd":"https:\/\/c.aaxads.com","pub":"AAX763KC6","gdpr":"0","gdprconsent":"1","uspst":"0","uspcn":"","icr":"0","feedbackConfig":{"adIconConfig":{"206":{"id":"206","text":"ad","css":"background-color: #ffffff; color: #000000; border-color: #a1a1a1;"},"209":{"id":"209","text":"AD","css":"background-color: #ffffff; color: #0071bc; border-color: #ffffff;"},"212":{"id":"212","text":"ad","css":"background-color: rgba(0,0,0,.55); color: #ffffff; border-color: #ffffff;"},"241":{"id":"241","text":"AD","css":"background-color: #ffffff; color: #000000; border-color: #a1a1a1;"},"250":{"id":"250","text":"Ad","css":"background-color: rgba(0,0,0,.55); color: #ffffff; border-color: #ffffff;"}}},"logUrls":{"og":"https:\/\/l3.aaxads.com\/log","aaxdbg":"___stu13p=aveoaamactga5dnnuee25racpo4cuud1vi7rv"}};
var na="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ua="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function va(){va=function(){};ua.Symbol||(ua.Symbol=Da)}var Da=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function Fa(){va();var a=ua.Symbol.iterator;a||(a=ua.Symbol.iterator=ua.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&na(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Ia(this)}});Fa=function(){}}function Ia(a){var b=0;return Ja(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function Ja(a){Fa();a={next:a};a[ua.Symbol.iterator]=function(){return this};return a}
function Ka(a,b){Fa();a instanceof String&&(a+="");var c=0,f={next:function(){if(c<a.length){var l=c++;return{value:b(l,a[l]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f}for(var La=ua,Ma=["Array","prototype","keys"],Na=0;Na<Ma.length-1;Na++){var Oa=Ma[Na];Oa in La||(La[Oa]={});La=La[Oa]}var Pa=Ma[Ma.length-1],Qa=La[Pa],Ra=Qa?Qa:function(){return Ka(this,function(a){return a})};
Ra!=Qa&&null!=Ra&&na(La,Pa,{configurable:!0,writable:!0,value:Ra});
(function(){function a(a){return"function"===typeof a}function b(b,c,g){a(c)&&(g=c,c=[]);if(void 0===b||""===b||null===b||"[object Array]"!==Object.prototype.toString.call(c)||!a(g))return!1;l[b]=l[b]||{uE:c,callback:g}}function c(b,k){var d=[],n;for(n in b)if(b.hasOwnProperty(n)){var h=b[n];"object"===typeof h||"undefined"===typeof h?d.push(h):(void 0===f[h]&&(f[h]=c(l[h].uE,l[h].callback)),d.push(f[h]))}return a(k)?k.apply(this,d):d}var f={},l={};var k="undefined"!==typeof global&&"object"===typeof module?
global:window;k.__ar=k.__ar||c;k.__ad=k.__ad||b})();
__ad("_",["pqus","uhv",window,document,{}],function(a,b,c,f){function l(a,b,c){b="evt_"+(b||"gbl");U[b]=U[b]||{};U[b][a]=U[b][a]||[];U[b][a].push(c)}function k(a){if(h(a)){var b="evt_"+a;h(U[b])&&!n(U[b])&&ea(U[b],function(a,c){U[b][c]=[]})}}function d(b,c,d,f){f=f||("object"===typeof d?d:{});d="boolean"===typeof d?d:!1;var g="evt_"+(c||"gbl");if(void 0!==U[g]){var h=U[g][b]||[],k={src:c};U.evt_gbl&&U.evt_gbl.gblEvt&&a.ca(U.evt_gbl.gblEvt[0],k,f);var l=0;for(c=h.length;l<c;l++)e(h[l])&&a.ca(h[l],
k,f);!d&&0<h.length&&(U[g][b]=[])}}function m(a,b){return h(a)?h(b)&&-1!==a.indexOf(b):!1}function g(a,b){return p(a)?W(a,function(a){if(a===b)return!0})||!1:!1}function n(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0}function h(a){switch(typeof a){case "string":return void 0!==a&&""!==a&&null!==a;case "object":return null!==a;case "number":case "boolean":return!0;default:return!1}}function e(a){return"function"===typeof a}function p(a){return"[object Array]"===Object.prototype.toString.call(a)}
function q(a){return h(a)?encodeURIComponent(a):""}function r(a){if(!h(a))return"";try{return decodeURIComponent(a)}catch(ca){return a}}function u(a){if(!h(a))return{};var b={};var c=a.indexOf("?");if(-1===c)return b;a=a.substring(c+1).split("&");for(c=a.length;c--;){var d=a[c].split("=");b[d[0]]=d[1]}return b}function t(a){this.url=a;this.map=u(this.url)}function w(){var a=!1;try{"object"===typeof c.top&&"object"===typeof c&&(a=c.top!=c)}catch(ca){a=!0}return a}function v(a,b){a=Math.floor(Math.random()*
(b-a+1)+a);a>b&&(a=b);return a}function x(a,b,c){c=c||null;b=b||[];return function(){var d=b.slice(0);0<arguments.length&&Array.prototype.push.apply(d,Array.prototype.slice.call(arguments));return a.apply(c,d)}}function y(a){try{var b=A(a);return[b&&(b.document||b)||!1,b,null]}catch(ja){return[!1,null,"Access Denied"]}}function A(a){try{return a.contentWindow||a.contentDocument}catch(ca){return null}}function C(a){var b;a=a.match(/^([1-9]\d*|0[0-7]*|0x[\da-f]+)(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?$/i);
if(!a)return!1;a[0]=0;for(b=1;5>b;b+=1)a[0]+=!!(a[b]||"").length,a[b]=parseInt(a[b],10)||0;a.push(256,256,256,256);a[4+a[0]]*=Math.pow(256,4-a[0]);return a[1]>=a[5]||a[2]>=a[6]||a[3]>=a[7]||a[4]>=a[8]?!1:a[1]*(1===a[0]||16777216)+a[2]*(2>=a[0]||65536)+a[3]*(3>=a[0]||256)+1*a[4]}function z(){return""+v(0,254)+"."+v(0,254)+"."+v(0,254)+"."+v(0,254)}function D(a,b,c,d,f){c=c||L("@body:0");if(!c)return N("@body:0",100,x(D,[a,b,null,d,f]),!1),null;var g=(new H).set("marginWidth",0).set("marginHeight",
0).set("scrolling","no").set("frameBorder",0).set("height",0).set("width",0).Kn("display:none !important;").done();h(a)&&(g.id=a);if(d)for(var k in d)g[k]=d[k];c.firstChild?c.insertBefore(g,c.firstChild):c.appendChild(g);b&&J(g,b);e(f)&&(g.onload=f);return g}function J(b,c){if(b){var d=y(b),e;try{if(null!==d[2])throw d[2];if(e=d[0])e.open(),e.write(c),e.close()}catch(Aa){d="javascript:var d=document.open();d.domain='"+f.domain+"';";b.src=d+"void(0);";try{var g=b.contentWindow.document;g.write(c);
g.close()}catch(ma){b.src=d+'d.write("'+c.replace(/"/g,'\\"')+'");d.close();',a.oa(ma)}}}}function K(a,b,c){if(!h(a))return"";h(c)&&h(c.encode)&&!0===c.encode&&(b=q(b));return"&"+a+"="+b}function S(){return/msie|rv:11\.0/.test(X.toLowerCase())}function I(a){var b=[];ea(a.split("&"),function(a){-1!==a.indexOf("=")&&""!==a&&"action_object_map="!==a.substring(0,18)&&"action_type_map="!==a.substring(0,16)&&"action_ref_map="!==a.substring(0,15)&&"action_action_map="!==a.substring(0,18)&&"fb_"!==a.substring(0,
3)&&"fbclid"!==a.substring(0,6)&&"lcid="!==a.substring(0,5)&&"force_hbtest="!==a.substring(0,13)&&"mnet_test="!==a.substring(0,10)&&"force_hbprv="!==a.substring(0,12)&&"a="!==a.substring(0,2)&&"kwp_0"!==a.substring(0,6)&&"utm_"!==a.substring(0,4)&&"code="!==a.substring(0,5)&&"bcmt"!==a.substring(0,4)&&b.push(a)});return b.join("&")}function P(){if(m(X,"Trident")||m(X,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(X);if(h(a)&&h(a[1]))return parseFloat(a[1])}return-1}function B(a,b){var d=/interactive|complete|loaded/;
f.attachEvent&&10>=P()&&(d=/complete|loaded/);if(d.test(f.readyState))a();else if(b||fa.V(c,"load",a),!b&&f.addEventListener)fa.V(f,"DOMContentLoaded",a);else if((b=f.documentElement)&&b.doScroll)try{b.doScroll("left"),a()}catch(sa){setTimeout(x(B,[a,!0]),50)}}function H(a){this.frame=a?a.document.createElement("iframe"):f.createElement("iframe")}function L(a){try{var b=a.substr(1).split(":"),c=b[0],d=h(b[1])&&parseInt(b[1],10);switch(a.charAt(0)){case "@":var e=f.getElementsByTagName(c);break;case "#":e=
f.getElementById(c);break;case "$":e=f.getElementsByName(c);break;case ".":e=V(f,c);break;default:e=f.getElementById(a)}return!1===d?e:e[d]}catch(Aa){return null}}function N(a,b,c,d){try{var e=L(a),f=ra.kc().Um();e||!d&&f?c.call(null,e||!1):setTimeout(x(N,[a,b,c,d]),b)}catch(ma){setTimeout(x(N,[a,b,c,d]),b)}}function V(a,b,c){if(e(f.getElementsByClassName))return a.getElementsByClassName(b);c=c||"*";b=new RegExp("(^|\\s)"+b+"(\\s|$)");a=a||f;c="*"===c&&a.all?a.all:a.getElementsByTagName(c);a=[];var d=
c.length,g;for(g=0;g<d;g++){var h=c[g];b.test(h.className)&&a.push(h)}return a}function M(){return h(X)&&/ip(hone|od|ad)|android|blackberry|kindle|symbian|wap|windows (ce|phone)|palm( os)|iemobile|nokia|mobile/i.test(X)}function aa(){if(m(X,"Gecko")&&!m(X,"Trident")&&!m(X,"MSIE")||m(X,"webkit"))return!0;if(m(X,"Trident")||m(X,"MSIE")){var a=P();if(11<=a)return!0}return!1}function P(){if(m(X,"Trident")||m(X,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(X);if(h(a)&&h(a[1]))return parseFloat(a[1])}return-1}
function Y(a){var b=a.toString(),c=b.indexOf(".");return-1!==c?parseFloat(b.substr(0,Math.min(c+3,b.length))).toFixed(2):parseFloat(a).toFixed(2)}function ba(a){return h(a)?!isFinite(a)||isNaN(a)?0:a:0}function da(){return-1!==c.location.href.indexOf("aax_test=")}function ia(a,b){if(null===b||"object"!==typeof b||!h(a))return b;ea(b,function(b,c){a[c]=ia(a[c],b)});return a}function ea(a,b){if(h(a)){var c=0,d=a.length;if(p(a))for(;c<d;c++)b.call(a[c],a[c],c,d);else for(c in a)a.hasOwnProperty(c)&&
b.call(a[c],a[c],c,0)}}function W(a,b){if(h(a)){e(b)||(b=function(a){return!!a});var c=0,d=a.length;if(p(a))for(;c<d;c++){var f=b.call(a[c],a[c],c);if(h(f))return f}else for(c in a)if(a.hasOwnProperty(c)&&(f=b.call(a[c],a[c],c),h(f)))return f}}function ha(a,b){if(!h(a))return[];var c;e(b)||(b=function(a){return!!a});var d=0,f=a.length;if(p(a))for(c=[];d<f;d++)c.push(b.call(a[d],a[d],d));else for(d in c={},a)a.hasOwnProperty(d)&&(c[d]=b.call(a[d],a[d],d));return c}function F(a){return"CSS1Compat"==
a.compatMode?a.documentElement:a.body}function G(a){var b=a.document,c=void 0,d=void 0;try{var e=F(b);if(!e){b.write('<div id="_mNTemp" style="display:none;"></div>');e=F(a.document);var g=f.getElementById("_mNTemp");g.parentNode.removeChild(g)}e&&(c=e.clientWidth||void 0,d=e.clientHeight||void 0)}catch(ma){}return{width:c,height:d}}function ka(){return!!(c.JSON&&c.JSON.parse&&"function"===typeof JSON.parse&&c.JSON.stringify&&"function"===typeof JSON.stringify)}function Q(){return(new Date).getTime()}
function O(a,b,c){c=c||"0";for(a+="";a.length<b;)a+=c;return a}function T(a,b){a=parseInt(a);return!isFinite(a)||isNaN(a)?b:a}function R(){return{TC:c.pageXOffset||c.scrollX,lr:c.pageYOffset||c.scrollY}}function Z(a){return null===a||"boolean"===typeof a||"number"===typeof a||"string"===typeof a||"symbol"===typeof a||"undefined"===typeof a}function la(a,b,c){la.count=la.count||0;la.threshold=la.threshold||c;setTimeout(function(){a.call(this);h(la.threshold)?(la.count++,la.count<la.threshold&&la(a,
b,c)):la(a,b,c)},b)}function Ea(a,b){ea(b,function(b,c){Z(b)||p(b)||!a.hasOwnProperty(c)?a[c]=b:a[c]=Ea(a[c],b)});return a}function Ca(a){return W(a,function(a){if(null!==a&&"object"===typeof a)return!0})||!1}function xa(a){if(!h(a))return a;var b=p(a)?[]:{};if(!Ca(a))return ea(a,function(a,c){b[c]=a}),b;ea(a,function(a,c){if(p(a)){var d=Ca(a)?xa(a):a.slice();b[c]=d}b[c]=null!==a&&"object"===typeof a?xa(a):a});return b}function ya(a){if(ka())return JSON.stringify(a);if(!h(a)||"object"!==typeof a)return null===
a?a+"":a;var b="";ea(a,function(c,d){void 0!==c&&("object"===typeof c&&(c=ya(c)),b=p(a)?b+c:b+(d+":"+c),b+=",")});b=b.slice(0,b.length-1);return p(a)?"["+b+"]":"{"+b+"}"}function pa(){try{if("localStorage"in c&&null!==c.localStorage)return c.localStorage.setItem("mntest","mntest"),c.localStorage.removeItem("mntest"),ka()}catch(E){}return!1}function za(a,b){var c=0;ha(a,function(a){b&&a[b]&&(c+=a[b])});return c}var U={},X=navigator.userAgent,qa=Math.random(),fa={V:function(a,b,c){a.addEventListener?
a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},uj:function(a,b,c){a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)}};t.prototype.CG=function(){var a=this.map.dn;return a&&r(a)||""};var ra=function(){function b(){function b(){for(d=!0;0<e.length;){var a=e.shift();a.call(null)}e=[]}function c(){a.ca(b)}var e=[];this.gd=function(a){e.push(a);1!==e.length||d?d&&c():B(c)};this.Um=function(){return d}}var c=null,d=!1;return{kc:function(){null===
c&&(c=new b);return c}}}();H.prototype.set=function(a,b){this.frame[a]=b;return this};H.prototype.Kn=function(a){this.frame.style.cssText=a;return this};H.prototype.done=function(){return this.frame};return{xf:function(a){var b=f.cookie.indexOf(a+"="),c=b+a.length+1;if(!b&&a!==f.cookie.substring(0,a.length)||-1===b)return null;a=f.cookie.indexOf(";",c);-1===a&&(a=f.cookie.length);return unescape(f.cookie.substring(c,a))},lo:function(a,b,c,d,e,g,h){var k=new Date;k.setTime(k.getTime());c&&(c*=864E5);
h&&(c=6E4*h);h=new Date(k.getTime()+c);f.cookie=a+"="+escape(b)+(c?";expires="+h.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(g?";secure":"")},Ln:O,O:q,wc:r,Rv:function(a){return r(a)!==a},nL:function(a){return m(X.toLowerCase(),a)},oO:function(a){var b=a.length;for(a=(a||"0123456789abcdefghijklmnopqrstuvwxyz").split("");b;){var c=Math.floor(Math.random()*b);--b;var d=a[b];a[b]=a[c];a[c]=d}return a.join("")},Yc:function(a,b){return!h(a)&&h(b)?null:(a=(new RegExp("[?&]"+b+"=([^&#]*)","i")).exec(a))?
a[1]:null},Bc:function(a){a=r(a);return(a=a.match(/^http(?:s)?:\/\/([^/]+)/im))?a[1].toString():""},N:function(){return h(c.location.href)?c.location.href:""},ph:function(a){return"string"===typeof a},Mv:function(a){return"boolean"===typeof a},L:function(a){return h(a)},Ec:w(),Bga:w,ta:v,Cu:function(a,b,c){c=Math.pow(10,c||2);return v(a*c,b*c)/c},wG:function(){var a=new Date;a=new Date(Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()));var b=new Date(Date.UTC(a.getUTCFullYear(),0,1));a.setUTCDate(a.getUTCDate()+
4-(a.getUTCDay()||7));return Math.ceil(((a-b)/864E5+1)/7)},xm:u,Xz:t,SD:function(a){return h(a)?-1!==a.search("^(http(s)?%253A%252F%252F)")?r(a):-1!==a.search("^(http(s)?://)")?q(a):a:""},X:fa,i:e,isArray:p,Gj:c.navigator.userAgent.toLowerCase(),tK:aa(),xa:function(a,b,c){var d={};h(c)&&h(c.encode)&&(d.encode=c.encode);c="";var e,f=!!b,g=f?b:a,k;for(e in g)if(g.hasOwnProperty(e)){f&&(e=b[e]);if(k=h(a[e]))k=a[e],k="object"!==typeof k||!1!==k.qL;if(k)if(p(a[e]))for(var l in a[e])c+=K(e+"[]",a[e][l],
d);else k="object"===typeof a[e]?a[e].value:a[e],c+=K(e,k,d)}return c},Aa:K,Dga:function(a){switch(typeof a){case "string":return h(a)&&("1"===a||"true"===a);case "number":return 0!==a;case "boolean":return a;default:return!1}},$:g,Af:y,Pg:A,C:x,Xj:H,Rc:N,ic:V,Fv:C,EN:function(a){var b=a.lastIndexOf(".");return-1===b?"":a.substr(0,b+1)+"0"},uc:m,U:L,bf:function(a,b){a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},Uw:function(a){a.parentNode.removeChild(a)},Se:J,Oga:function(a,b){J(a,
'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; }};scriptElement.src = "'+b+'"; tag.parentNode.insertBefore(scriptElement, tag);}\x3c/script></head><body onload="makeCall()"></body></html>')},
Dha:function(a,b){if(void 0!==a&&void 0!==b&&void 0!==a[b])return a[b]},Kc:ra,Cga:M,SK:function(){return h(X)&&/mac_powerpc|macintosh|mac\\sos|darwin\/|imac\/|macbookpro[\d]/i.test(X)},ud:D,qh:function(b,c,d,e){if(h(b)){"http"!==b.substr(0,4)&&!0===d&&(b=("https:"===f.location.protocol?"https:":"http:")+b);d=f.createElement("script");var g=f.getElementsByTagName("script")[0],k=!1;d.type="text/javascript";d.async=!0;e&&e.crossOrigin&&(d.crossOrigin="anonymous");c&&"function"===typeof c&&(d.onload=
d.onreadystatechange=function(){k||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(k=!0,a.ca(c))});d.src=b;g.parentNode.insertBefore(d,g)}},bj:function(a){if(h(a)){var b=f.createElement("script"),c=f.getElementsByTagName("script")[0];b.type="text/javascript";b.appendChild(f.createTextNode(a));c.parentNode.insertBefore(b,c)}},AL:function(a,b,c){if(h(a)){"http"!==a.substr(0,4)&&(a=("https:"===f.location.protocol?"https:":"http:")+a);var d="aax_if"+c;l("prvreq",c,b);a=D(d,
'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
c+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');return y(a)[1]}},triggerEvent:d,Wx:function(a,b,c,e){d("b:"+a,
b,c);d(a,b,c,e);d("a:"+a,b,c)},B:l,sga:function(a,b,c){var d=!1;p(a)&&h(b)&&h(c)&&(ea(a,function(e,f){!0===(new RegExp(b)).test(e)&&(d=!0,a[f]=c)}),!1===d&&a.push(c))},pa:Y,hf:function(){da()&&c.console&&c.console.log(Array.prototype.slice.call(arguments))},qn:da,Du:z,Zea:function(a,b,c){var d=[],e,f=[],g={};if(0===a.length)return[""];h(c)&&h(c.encode)&&(g.encode=c.encode);for(m in a[0])a[0].hasOwnProperty(m)&&d.push(m);var k="",l=S();var m=0;for(c=a.length;m<c;m++){var n="";var p=0;for(e=d.length;p<
e;p++)n+=K(d[p]+"[]",a[m][d[p]],g);l&&h(b)?n.length>b?f.push(n):(k+n).length>b?(f.push(k),k=n):k+=n:k+=n}f.push(k);return f},ui:function(a,b){var c="",d={};h(b)&&h(b.encode)&&(d.encode=b.encode);ea(a,function(a,b){c+=K(b,a,d)});return c},u:function(a,b){a.Zha=b;for(var c in b.prototype)a.prototype[c]=b.prototype[c];a.prototype.constructor=a},kj:function(a,b){b*=6E4;return Q()-a>b?!1:!0},D:new function(){var a={},b,c=!1;this.startTime=function(){return b};this.start=function(){b=(new Date).getTime();
c=!0};this.stop=function(){(new Date).getTime();c=!1};this.Wc=function(){return(new Date).getTime()-b};this.ha=function(b){a[b]={};a[b].startTime=c?this.Wc():-1};this.qa=function(b){a.hasOwnProperty(b)&&(a[b].endTime=-1===a[b].startTime?-1:this.Wc())};this.time=function(b){return a.hasOwnProperty(b)?(a[b].endTime||this.qa(b),a[b].endTime-a[b].startTime):-1};this.getTime=function(b){return a.hasOwnProperty(b)?this.Wc()-a[b].startTime:-1}},extend:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=
b[c]);return a},Rn:ia,Hb:function(){try{return/loaded|complete/.test(f.readyState)}catch(E){return!1}},Efa:function(a,b){b="evt_"+(b||"gbl");U[b]&&U[b][a]&&0<U[b][a].length&&(U[b][a]=[])},wha:function(){for(var a in U)U.hasOwnProperty(a)&&-1!==a.indexOf("evt_")&&-1===a.indexOf("cmd")&&(U[a]={})},xha:k,yha:function(){k("gbl")},a:h,pK:function(a){return"undefined"!==typeof a},trim:function(a){return h(a)?a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):""},I:n,Md:function(a){return"object"===typeof a&&
null!==a&&!n(a)},Qr:function(a){if(!p(a))return{};for(var b=0,c=a.length,d={};b<c;b++)d[a[b]]=b+1;return d},map:ha,reduce:function(a,b,c){if(e(b)){if(p(a)){var d=0;var f=a.length;if("undefined"===typeof c){for(;d<f&&!(d in a);)d++;if(d>=f)return;c=a[d++]}for(;d<f;d++)d in a&&(c=b(c,a[d],d,a));return c}c=c||"";for(d in a)a.hasOwnProperty(d)&&(c=b(c,a[d],d,a));return c}},filter:function(a,b){if(!h(a))return[];var c;e(b)||(b=function(a){return!!a});var d=0,f=a.length;if(p(a))for(c=[];d<f;d++)b.call(a[d],
a[d],d)&&c.push(a[d]);else for(d in c={},a)a.hasOwnProperty(d)&&b.call(a[d],a[d],d)&&(c[d]=a[d]);return c},Uc:function(a,b){b=b.split(".");var c;for(c=0;c<b.length;++c){if(void 0===a[b[c]])return;a=a[b[c]]}return a},A:W,some:function(a,b){if(!h(a))return!1;e(b)||(b=function(a){return!!a});var c=0,d=a.length;if(p(a))for(;c<d;c++){var f=b.call(a[c],a[c],c);if(!0===f)return f}else for(c in a)if(a.hasOwnProperty(c)&&(f=b.call(a[c],a[c],c),!0===f))return f;return!1},c:ea,Zs:S,ue:G,Ig:function(){return G(c).width},
Yl:function(){return G(c).height},TI:function(){try{return c.screen.width+"x"+c.screen.height}catch(E){return""}},Of:ka,da:Q,xh:function(a,b){b=Math.pow(10,b);return Math.round(a*b)/b},Zf:function(a){return(a||"").replace(/\/$/,"")},Ti:function(a){if(e(Object.keys))return Object.keys(a);var b=[];ea(a,function(a,c){b.push(c)});return b},IH:function(a){if(p(a)&&(a=Math.max.apply(null,a),!isNaN(a)))return a},Vga:function(a,b){if("object"!==typeof a||"string"!==typeof b)return!1;if("string"===typeof a.className)return(new RegExp("(^|\\s)"+
b+"(\\s|$)")).test(a.className)},Ud:function(a,b,c){var d=e(c)?c:Date.now,f=d();return function(){var c=d();c-f>=a&&(f=c,b.apply(null,arguments))}},Na:function(a,b){return a.style[b]?a.style[b]:a.currentStyle?a.currentStyle[b]:f.defaultView&&f.defaultView.getComputedStyle?(b=b.replace(/([A-Z])/g,"-$1"),b=b.toLowerCase(),(a=f.defaultView.getComputedStyle(a,""))&&a.getPropertyValue(b)):null},Jx:function(a){h(a)&&(a.style.cssText=(a.style.cssText||"")+";display:block!important;")},pv:function(a){h(a)&&
(a.style.cssText=(a.style.cssText||"")+";display:none!important;")},yi:function(d,e,f,g){function k(){(f.onerror||m)()}function l(){(f.onload||m)(n.response||n.responseText)}function m(){}if(!c.XMLHttpRequest)return(f.Gl||m)(),null;var n=new XMLHttpRequest,p=!1;d=(d||b.fz.Y7).toUpperCase();if("withCredentials"in n)n.open(d,e,!0),n.withCredentials=h(f.withCredentials)?f.withCredentials:!0;else if(c.XDomainRequest){n=new XDomainRequest;try{n.open(d,e)}catch(Ha){return(f.Gl||m)(),null}}else return(f.Gl||
m)(),null;n.onload=n.onreadystatechange=function(){p||4!=n.readyState||(200==n.status?a.ca(l):k(),p=!0)};n.onerror=k;n.onabort=k;n.send(g);return!0},cu:P,zm:function(a){var b;try{a&&a.data&&"string"===typeof a.data&&ka()&&(b=JSON.parse(a.data))}catch(ja){}return b},xn:function(){return e(c.navigator.sendBeacon)?!0:!1},lK:function(){return"withCredentials"in new XMLHttpRequest||"undefined"!=typeof XDomainRequest?!0:!1},pH:function(a){function b(a){a=a.match(/\d+/g);return null===a||0===a.length?"":
a[0]}a=a.frameElement;var c=String(a.height||"0"),d=String(a.width||"0");-1!==c.indexOf("%")||-1!==d.indexOf("%")?(d=a.getBoundingClientRect&&a.getBoundingClientRect()||{},c=Math.ceil(d.height||a.clientHeight)||0,d=Math.ceil(d.width||a.clientWidth)||0):(c=b(c),d=b(d));return d+"x"+c},jJ:function(){try{var a=c.localStorage}catch(ca){}return h(a)&&(a=a.getItem("tpck"),h(a))?a:!1===(c&&c.navigator&&c.navigator.cookieEnabled||navigator&&navigator.cookieEnabled)?0:""},Ot:function(a){a=L("#"+a);var b={},
c=R().TC,d=R().lr,f={};h(a)&&e(a.getBoundingClientRect)&&(f=a.getBoundingClientRect());b.dia=T(f.top,0);b.Uea=T(f.bottom,0);b.Nga=T(f.left,0);b.Aha=T(f.right,0);b.top=T(f.top+d,0);b.bottom=T(f.bottom+d,0);b.left=T(f.left+c,0);b.right=T(f.right+c,0);b.offsetX=T(c,0);b.offsetY=T(d,0);return b},Pa:function(){var a=Array.prototype.slice.call(arguments),b=a[0];a.shift();ea(a,function(a){p(a)?Array.prototype.push.apply(b,a):b.push(a)});return b},Ya:T,Request:function(a){var b={};this.input=function(a,c){b[a]=
c;return this};this.get=function(a){return h(b[a])?b[a]:""};this.qw=function(a){a&&(b=a);return this};this.freeze=function(){return b};this.deleteProperty=function(a){delete b[a]};a&&(b=a)},ls:function(a){if(!h(a))return"";var b=a.split("?")[0].split("#")[0];if(!h(b))return"";b=b.replace(/\/$/,"");var c=a.indexOf("#"),d="";0<c&&(d=a.substring(c+1));var e=a.indexOf("?");c=0<c?c:a.length;var f="";0<e&&(f=a.substring(e+1,c));a=I(f);h(a)&&(b=b+"?"+a);d=I(d);h(d)&&(b=b+"#"+d);return b},hM:function(a,b){try{return aa()?
(a.document.write(b),a.document.close()):(a.hbContent="<!DOCTYPE html><html><head></head><body>"+b+"</body></html>",a.location.replace('javascript:window["hbContent"];')),!0}catch(ja){return!1}},jf:function(a,b,c){return(new H).set("marginWidth",0).set("marginHeight",0).set("scrolling","no").set("frameBorder",0).set("height",c||0).set("width",b||0).set("id",a).set("allowtransparency","true").done()},un:Z,mD:function(a,b){h(b)||(b=0);return new Date(a.getTime()+6E4*b)},lM:la,M:function(b,c){return"function"===
typeof b?x(a.ca,[c||null,b]):b},Ui:function(){try{var a=c.document.body,b=c.document.documentElement;return Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,b.offsetHeight)}catch(ja){return 0}},Gga:function(){return!1},la:function(){return O(C(z()),10)+""+v(1E6,9999999)+""+(new Date).getTime().toString()},Mb:function(a,b){return a*(1+b/100)},dx:ba,getFloatValue:function(a){a=ba(a);a=Y(a);return parseFloat(a)},Mw:Ea,Cs:xa,Xb:function(a){return h(a)&&(1>a||1<a*qa)},Xg:function(){return("https:"===
c.location.protocol?"https:":"http:")+"//"+c.location.hostname},PL:ya,dl:function(a){return"http"!==a.substr(0,4)?("https:"===f.location.protocol?"https:":"http:")+a+a:a},KO:function(a,b){return a.length>b?a.substr(0,b):a},XH:R,mJ:function(a){for(var b=a.parent;b!==c.top;)a=a.parent,b=b.parent;return a},Rfa:function(a){(new Image).src=a},postMessage:function(a,b,d){var g=A(d);b&&h(g)&&(c.postMessage&&e(g.postMessage)?g.postMessage(a,"*"):b&&("object"===typeof a&&(a=ya(a),a=escape(a)),b=b+"#"+f.location.href,
d.src=b,g.location=b.replace(/#.*$/,"")+"#_CPM$"+a))},AK:function(){return!!c.EventSource},Oe:pa,$i:function(){return M()&&!pa()},pI:function(a,b){if(b){var c=za(a,b),d=v(0,100),e=0,f=null;return 1>c||100<c?f:f=W(a,function(a){if(a[b]&&(e+=a[b],d<e))return a})}},fs:function(a,b){return p(a)&&p(b)?W(a,function(a){return g(b,a)}):!1},pJ:function(){return c.navigator&&c.navigator.vendor},nh:function(){if(-1!==navigator.userAgent.indexOf("CriOS")||-1!==navigator.userAgent.indexOf("FxiOS"))return!1;var a=
navigator.userAgent.toLowerCase();a=-1!==a.indexOf("safari")&&-1===a.indexOf("chrome")||!1;return navigator.vendor&&-1<navigator.vendor.indexOf("Apple")||a},iH:function(a){var b=L("@head:0");if(b)return b.getAttribute(a)||""},OG:function(a){return h(a)&&"undefined"!==typeof a?a.getAttribute("id")||a.id:""},vj:function(a,b,c){return a.replace(new RegExp(b,"g"),c)},gm:function(a){for(var b=c,d;b;){try{if(b.frames[a]){d=b;break}}catch(sa){}if(b===c.top)break;b=b.parent}return d},bH:function(a){return a.frameElement}}});
__ad("pqus",[window,document,{}],function(a,b){function c(){var f,k=0;for(f=0;3>f;f++)k+=e[f].length;if(0!==k){var l=new Image,n=("https:"===b.location.protocol?"https":"http")+"://l3.aaxads.com/nerrping.php",t="",w=0;for(f=2;0<=f;f--){for(k=e[f].length;0<k;){var v=1===f?e[f][0]:{logLevel:e[f][0].logLevel,errorVal:{name:e[f][0].errorVal.name,type:m,svr:g,message:e[f][0].errorVal.message,line:e[f][0].errorVal.lineNumber,description:e[f][0].errorVal.description,stack:e[f][0].errorVal.stack}};v="object"===
typeof JSON&&"function"===typeof JSON.stringify?JSON.stringify(v):void 0;if(1200>=v.length+t.length||!t.length)0!==t.length&&(t+=","),t+=v,e[f].shift(),k--;else{w=1;break}}if(w)break}t=encodeURIComponent("["+t+"]");f=n+"?d="+t+"&userAgent="+h+"&requrl="+encodeURIComponent(a.location.href)+"&img=logo.gif";l.src=f}d(c,2500)}function f(a){"undefined"===typeof a.logLevel&&(a={logLevel:3,errorVal:a});3<=a.logLevel&&e[a.logLevel-1].push(a)}function l(a,b,c){this.name=a;this.message=b;this.logLevel=c}function k(){var a=
Array.prototype.slice.call(arguments),b=a.length,c=null,d=null;if("object"===typeof a[b-1]&&null!==a[b-1]&&a[b-1].constructor===l){var e=a[b-1];b--}if("function"===typeof a[0]){var g=a.shift();b--}else c=a.shift(),g=a.shift(),b-=2;a=a.slice(0,b);try{return g.apply(c,a)}catch(v){return e&&(v.name=e.name+" ("+v.name+")",v.message=e.message+" ("+v.message+")",d=e.logLevel),f({logLevel:d||3,errorVal:v}),new l}}function d(b,c){if("function"===typeof b)return a.setTimeout(function(){k(b)},c)}var m="",g=
"",n,h=encodeURIComponent(navigator.userAgent),e=[];for(n=0;3>n;n++)e[n]=[];a.addEventListener("load",c);return{ca:k,oa:f,Ih:function(a){m=a},lx:function(a){g=a},Qha:function(){},setTimeout:d}});
__ad("qlf",["pqus",window,"_","uhv","performanceobserver"],function(a,b,c,f,l){function k(a){var b=c.extend({},h);return a=c.extend(b,a)}function d(b,d,f){!0===d.Ws&&(b=c.dl(b));c.a(d.Rr)&&c.c(d.Rr,function(a,b){e.setAttribute(b,a)});var e=document.createElement("script");d=document.getElementsByTagName("script")[0];var g=!1;e.type="text/javascript";e.async=!0;f&&"function"===typeof f&&(e.onload=e.onreadystatechange=function(){g||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||
(g=!0,a.ca(f))},e.onerror=function(){f.call(null,"error")});e.src=b;d.parentNode.insertBefore(e,d)}function m(a,b){var d=new Image;a=c.KO(a,8E3);d.onload=b;d.src=a;d.onerror=function(){b.call(null,"error")}}function g(a,b){var d=new XMLHttpRequest,e="POST"===b.method?a.url:a;if(!("withCredentials"in d))return d=new XDomainRequest,d.open(b.method,a),d;d.open(b.method,e,!0);d.withCredentials=c.a(b.withCredentials)?b.withCredentials:!0;return d}function n(a,b,c){var d=!1,e=a.payload;try{var f=g(a,b)}catch(w){c.call(null,
500,"error")}f.onload=f.onreadystatechange=function(){if(!d&&4===this.readyState)return d=!0,200===this.status?c.call(null,null,this.response||this.responseText):c.call(null,this.state,"error")};f.send(e)}var h={Y:["plvf"],method:"GET",type:"img",Ws:!1};return{submit:function(a,f,g){c.isArray(a)||(a=[a]);f=k(f);g=g||function(){};c.c(a,function(a){var e=l.C(a,f,g);switch(f.type){case "img":m(a,e);break;case "script":d(a,f,e);break;case "xhr":n(a,f,e);break;case "sb":e=f;c.xn()&&(a=!1===b.navigator.sendBeacon(a.url,
a.payload)?"error":"success",l.Hr(e,a));break;case "ifScr":var h=f;a=c.dl(a);c.B("prvreq",h.name,e);a=c.ud("",'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
h.name+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');c.Af(a)}})},stream:function(a,c,d){d=d||function(){};c=k(c);
var e=l.C(a,c,d);try{var f=new b.EventSource(a,{withCredentials:!0})}catch(t){e.call(null,"error")}"undefined"!==typeof f&&(f.onopen=e,f.onerror=function(){e.call(null,"error")});return f}}});
__ad("performanceobserver",function(){return{C:function(a,b,c){return c},Hr:function(){}}});
__ad("postmessagemanager","_ qlf srvwpf pqus ef ie postdata inmemdatasource ff uhv".split(" "),function(a,b,c,f,l,k,d,m){function g(b,c){a.c(c,function(a,c){b.setTargeting(c,a)})}function n(b){a.c(b,function(a,b){window.googletag.pubads().setTargeting(b,a)})}function h(b,c,e,d,h,f){window.googletag.cmd.push(function(){x=window.googletag.defineSlot(b,d,"aax_standard").addService(window.googletag.pubads());window.googletag.pubads().set("page_url",m.get("referer"));window.googletag.pubads().set("adsense_ad_types",
"text");var k={};!0===m.get("icr")&&(k.childDirectedTreatment=!0);!0===m.get("uspst")&&!0!==m.get("uspcn")&&(k.restrictDataProcessing=!0);a.a(f)&&window.googletag.pubads().setRequestNonPersonalizedAds(f);a.I(k)||window.googletag.pubads().setPrivacySettings(k);window.googletag.enableServices();A.enqueue("aax_standard",h);g(x,c);n(e);a.Rc("#aax_standard",100,function(){window.googletag.display("aax_standard")},!0)})}function e(c){var e=m.for(c).get("isAAX"),h=m.for(c).get("dfpData"),g="1"===m.for(c).get("sRdOut"),
f=!0===m.for(c).get("iwr"),k=m.for(c).get("reSz");a.a(h)&&(g=(new d).set("dfpadvid",h.advertiserId).set("dfpcmpid",h.campaignId).set("crtid",h.creativeId).set("liid",h.lineItemId).set("lbid",h.labelIds).set("isbckfl",h.isBackfill).set("isEmp",h.isEmpty).set("sz",h.dfpDivSize).set("srcAgnCrid",h.sourceAgnosticCreativeId).set("srcAgnLid",h.sourceAgnosticLineItemId).set("srvcnm",h.serviceName).set("auPt",m.get("auPt")).set("aId",c).set("isAaxWon",e).set("sRdOut",g).set("type","renderad").set("iwr",f).set("reSz",
k),e||g.set("adc",h.adcode),g.target(m.get("tarOg")),g.Rb(m.get("fid")),window.top.postMessage(g.Z(),g.target()),e=m.for(c).get("status")||!1,c=m.for(c).get("lpx"),e&&c&&b.submit(c,{type:"img",Y:["win","plvf"]}))}function p(a){var b=a.get("pvid");a=a.get("aId");"207"===b?m.for(a).set("sRdOut","1"):m.for(a).set("sRdOut","0")}function q(a){var b=a.get("ac"),c=a.get("lpx"),e=a.get("tarM"),d=a.get("crid"),h=a.get("pvid"),f=a.get("aId");p(a);m.set("aid",f);m.for(f).set("adCode",b).set("lpx",c).set("isAAX",
!1).set("crid",d).set("pvid",h);window.googletag.cmd.push(function(){x.clearTargeting();A.enqueue("aax_standard",f);g(x,e);window.googletag.pubads().refresh([x])})}function r(b,c){b=(new d).Qb(c.data);switch(b.get("type")){case "refReq":q(b);break;case "initRen":c=b.get("aId");var e=b.get("ac"),g=b.get("lpx"),f=b.get("tarM"),k=b.get("gtm"),l=b.get("szs"),n=b.get("crid"),r=b.get("pvid"),u=b.get("auPt"),t=b.get("npa"),y=b.get("ncp");var v=b.get("tcf");t=a.a(t)||v?a.a(y)&&"1"===y||"1"===t?parseInt(t):
void 0:m.get("gdpr")?1:"";y=b.get("renIW")||!1;p(b);m.set("aid",c);m.set("auPt",u);m.for(c).set("isAAX",!1).set("lpx",g).set("adCode",e).set("crid",n).set("pvid",r).set("renIW",y);h(u,f,k,l,c,t)}}function u(){var b=m.get("aid"),c=m.for(b).get("isAAX"),e=m.for(b).get("crid");b=m.for(b).get("pvid");c||(b="-1");a.a(y)?y.$w():y=k.an(window,b);k.es(e,b)}function t(b){var c=b.slot,d={};try{var h=c.getTargetingMap()}catch(H){}var g=h?h:d;var k=c.getResponseInformation()||{};d=g.aax_ausz;h=A.zi("aax_standard");
g.slotElementId=c.getSlotElementId();g.advertiserId=k.advertiserId||"";g.campaignId=k.campaignId||"";g.creativeId=k.creativeId||"";g.labelIds=k.labelIds||[];g.lineItemId=k.lineItemId||"";g.isBackfill=k.isBackfill?"1":"0";g.dfpDivSize=a.isArray(b.size)?b.size.join("x"):"";g.serviceName=b.serviceName||"";g.isEmpty=b.isEmpty?"1":"0";g.sourceAgnosticCreativeId=b.sourceAgnosticCreativeId||"";g.sourceAgnosticLineItemId=b.sourceAgnosticLineItemId||"";b=a.U("#aax_standard");if(a.a(b)){b:{b=b.getElementsByTagName("iframe")[0];
try{if(!a.a(b)&&!a.a(b.contentDocument)){var l=null;break b}var p=b.contentDocument;l=a.a(p)&&0!==p.getElementsByTagName("html").length?p.getElementsByTagName("html")[0]:null;break b}catch(H){}l=void 0}l=a.a(l)?l.innerHTML:""}else l="";g.adcode=l;m.for(h).set("dfpData",g);g=m.for(h).get("dfpData");l=m.for(h).get("crid");p=m.for(h).get("renIW");b="1"==g.isEmpty;g="";a.a(d)&&0<d.length&&(g=d[0]);if(b&&p&&a.L(g)&&(d=a.U("#aax_standard"),a.a(d)))if(d.innerHTML="",m.for(h).set("iwr",!0),m.for(h).set("reSz",
g),"1"===m.for(h).get("sRdOut"))m.for(h).set("status",!0);else{g=g.split("x");p=g[0];g=g[1];l="mnet_ifr_"+l;l=(new a.Xj).set("id",l).set("sandbox","allow-same-origin allow-forms allow-popups allow-scripts allow-pointer-lock allow-popups-to-escape-sandbox allow-top-navigation-by-user-activation").set("width",p).set("height",g).set("frameBorder","0").set("marginWidth","0").set("marginHeight","0").set("scrolling","no").done();l.style.cssText="display:block;";l.setAttribute("allowtransparency","true");
d.appendChild(l);d=m.for(h).get("adCode");try{l.contentDocument.open();l.contentDocument.write(d);l.contentDocument.close();var n=!0}catch(H){f.oa("Error while rendering the adcode"),n=!1}m.for(h).set("status",n)}(n=m.for(h).get("isAAX"))||(n=m.for(h).get("dfpData"),n=a.a(n)&&a.a(n.adcode)?-1!==n.adcode.indexOf("aax.deliverExchangeDemand"):!1);n?(m.for(h).set("isAAX",!0),e(h)):(n=250,a.a(m.get("pmdelay"))&&(n=m.get("pmdelay")),window.setTimeout(a.M(a.C(e,[h])),n))}function w(a){var b=new d;b.set("aId",
m.get("aid")).set("type","viewImpr").set("srvcnm",a.serviceName);b.target(m.get("tarOg"));b.Rb(m.get("fid"));window.top.postMessage(b.Z(),b.target())}function v(){function b(){window.googletag.pubads().addEventListener("slotRenderEnded",a.M(t));window.googletag.pubads().addEventListener("slotOnload",a.M(u));window.googletag.pubads().addEventListener("impressionViewable",a.M(w))}window.googletag&&window.googletag.cmd||(window.googletag=window.googletag||{},window.googletag.cmd=window.googletag.cmd||
[]);a.isArray(window.googletag.cmd)?window.googletag.cmd.unshift(b):window.googletag.cmd.push(b)}var x,y=null,A=new function(){var b={};this.enqueue=function(a,c){b[a]=b[a]||[];b[a].push(c)};this.zi=function(c){if(a.a(c)&&(c=b[c],a.a(c)&&a.isArray(c)&&0<c.length))return c.shift()}};return{init:function(){a.B("aaxOnMes","gbl",a.M(r));v()}}});
__ad("srvwpf",function(){return{F:{},be:{},Te:{}}});
__ad("ff",function(){return{PROVIDER_IDS:{},cp:{},Oz:{},Zz:{},Ca:{},Jz:{},hk:{},ZB:{},Ve:{},bB:{}}});
__ad("ef",function(){return{ak:{},bg:{},Uh:{},F:{},xk:{},Ak:{},Ye:{},$d:{},be:{}}});
__ad("of",function(){return{gi:{},Dp:{},rq:{},Bq:{},Eq:{},ty:{},Ab:{},bg:{},jk:{},qz:{},OC:{},hi:{},xB:{},Te:{},kk:{},Ye:{}}});
__ad("postdataconstants",function(){return{F:{}}});
__ad("uhv",function(){return{Event:{},ez:{},Gz:{},YA:{},LC:{},My:{},dz:{},hk:{},Te:{},FC:{}}});
__ad("wf",function(){return{Yj:{},bi:{}}});
__ad("aaxframelogmanager",[window.aaxSettings,"_","of","uhv","inmemdatasource"],function(a,b,c,f,l){return{Gea:function(c){var d={};d.hyw=c;d.flg=a.pub;d.jgsu=l.get("gdpr")?"1":"0";c=a.logUrls&&a.logUrls.og;var k=a.logUrls&&a.logUrls.aaxdbg;(new Image).src=c+"?"+k+b.xa(d)}}});
__ad("inmemdatasource",["_","uhv"],function(a){function b(){var b={};this.set=function(c,k){a.a(c)&&a.un(c)&&(b[c]=k);return this};this.get=function(a){return b[a]||""}}function c(c){if(!a.a(c)||!a.un(c))return null;c=c.toString();a.a(f[c])||(f[c]=new b);return f[c]}var f={},l={};return{set:function(a,b){return c("primary_in_mem_resource").set(a,b)},get:function(a){return c("primary_in_mem_resource").get(a)},$N:function(a,b){l[a]=b},fh:function(a){l[a]||(l[a]=[]);return l[a]},for:c}});
__ad("ie","feedbackuimanager _ srvwpf postdata ff uhv inmemdatasource".split(" "),function(a,b,c,f,l,k,d){function m(){var a={};this.input=function(c,e){var d=/[$]{([A-Za-z_]+)}/g.exec(c);b.a(d)&&b.isArray(d)&&d[1]&&(c=d[1]);a[c]=e;return this};this.qm=function(){return a}}function g(a,c){this.resolve=function(){return b.a(a)?a.replace(/[$]{([A-Za-z_]+)}/g,function(a,e){a=c[e];return b.a(a)?a:""}):""}}function n(a,c,e){if(!b.a(a)||!b.a(c)||!b.a(e))return!0;var d=b.some(a.placements,function(a){return a===
c});b.a(a.placements)||(d=!0);var h=b.some(a.providers,function(a){return a===e});b.a(a.providers)||(h=!0);return d&&h&&b.a(a.enabled)?a.enabled:!0}function h(a){a=(new f).set("type","feedback").set("aId",d.get("aid")).set("rate",a.Rd).set("dist",a.reason&&a.reason.distracting).set("ntRel",a.reason&&a.reason.notrelevant).set("prLb",a.reason&&a.reason.poorlylabeled).set("misL",a.reason&&a.reason.misleading).set("toob",a.reason&&a.reason.toobig);a.target(d.get("tarOg"));a.Rb(d.get("fid"));window.top.postMessage(a.Z(),
a.target())}function e(b){function c(){h(d.kt())}var e={Il:3,ux:!0,Tc:{right:"0px",bottom:"0px"},xw:"//c.aaxads.com",Fn:"v1"},d=a(e,b);d.CO(function(a){a>e.Il&&h(d.kt())});d.BO(c);d.AO(c);d.init();return d}return{an:function(a,c){var d=(b.a(a)?a:window).document,h='<span id="aax-ad-icon" class="advertisement-on-ad" ${ad_mark_block_css}>${ad_mark_block_text}</span>',k="AD",f="",l=(window.aaxSettings.feedbackConfig||{}).adIconConfig;b.a(c)&&b.a(l)&&(c=l[c],b.a(c)&&(b.a(c.text)&&(k=c.text),b.a(c.css)&&
(f='style="'+c.css+'"')));c=new m;c.input("${ad_mark_block_text}",k).input("${ad_mark_block_css}",f);h=(new g(h,c.qm())).resolve();k=d.createElement("div");for(k.innerHTML=h+'<div id="aax-feedback" class="container aax-popup hide"> <div class="popup-container"> <div class="logo-wrapper"> </div><div class="rating-block-wrapper"> <div class="aax-rating-block"> <div class="aax-rating hide"> <div class="aax-rating-text-wrapper"> <p class="aax-rating-text">We use user feedback to show better ads</p></div><div class="aax-stars-wrapper"> <p>Rate this Ad</p><ul class="star-list"> <li data-rate="5"></li><li data-rate="4"></li><li data-rate="3"></li><li data-rate="2"></li><li data-rate="1"></li></ul> </div></div><div class="aax-rating-feedback hide"> <ul class=""> <li> <label for="distracting"> <input type="checkbox" name="distracting" value="distracting" id="distracting"> <span class="checkmark"></span> Distracting </label> </li><li> <label for="poorlylabeled"> <input type="checkbox" name="poorlylabeled" value="poorlylabeled" id="poorlylabeled"> <span class="checkmark"></span> Poorly Labeled </label> </li></ul> <ul class=""> <li> <label for="toobig"> <input type="checkbox" name="toobig" value="toobig" id="toobig"> <span class="checkmark"></span> Too Big </label> </li><li> <label for="notrelevant"> <input type="checkbox" name="notrelevant" value="notrelevant" id="notrelevant"> <span class="checkmark"></span> Not Relevant </label> </li></ul> <ul class="last-column"> <li> <label for="misleading"> <input type="checkbox" name="misleading" value="misleading" id="misleading"> <span class="checkmark"></span> Misleading Ad </label> </li></ul> <span class="submit"> <button type="button" name="button">Submit</button> </span> </div><div class="aax-rating aax-rating-last hide"> <p> <i></i> <span>Thanks for submitting the feedback</span> </p></div></div></div><p class="aax-optout hide"> Cookies help us deliver our services better. Click here to <a href="https://optout.aaxads.com" target="_blank">Opt Out</a>. </p></div><span class="close-feedback"> <i></i> </span></div><span id="aax-feedback-icon" class="feedback-cta"> <i></i> </span>';k.firstChild;)d.body.appendChild(k.firstChild);
return e(a)},wr:function(a){a=(b.a(a)?a:window).document;var c=a.createElement("link");c.rel="stylesheet";c.type="text/css";c.href="//c.aaxads.com/aax-style.css";a.getElementsByTagName("head")[0].appendChild(c)},es:function(a,c){a=parseInt(a,10);c=parseInt(c,10);var e=b.U("#aax-ad-icon"),d=b.U("#aax-feedback-icon"),h=c,g=window.aaxSettings.feedbackConfig||{};c=n(g.adIcon,a,h);a=n(g.fdIcon,a,h);c?b.Jx(e):b.pv(e);a?b.Jx(d):b.pv(d)}}});
__ad("feedbackuimanager",function(){return function(a,b){a=a?a:{};if(b&&b.document){var c=b.document,f={top:"auto",right:"auto",bottom:"auto",left:"auto"},l={pb:"#aax-feedback",Il:3,ug:".feedback-cta",Po:null,Oo:null,ux:!1,Tc:null,xw:"images",Fn:null},k={},d={Rd:null,reason:{}},m=[],g=[],n=[],h={},e=!1,p=function(b,e){var d=c.querySelector(a.pb+" .logo-wrapper"),h=c.createElement("IMG");h.src=a.xw+"/"+e+(null===a.Fn?"":"?ver="+a.Fn);h.alt="AAX";h.className="portrait"===b?"logo logo-portrait":"logo logo-standard";
d.appendChild(h)},q={i:function(a){return"[object Function]"==={}.toString.call(a)},ri:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},CJ:function(a,b){return-1<a.className.indexOf(b)},de:function(a,b){if(!q.CJ(a,b)){var c=a.className.split(" ");c.push(b);a.className=c.join(" ")}return a},ld:function(a,b){a.className=a.className.replace(b,"").replace(/\s{2,}/g," ").replace(/^\s\s*/,"").replace(/\s\s*$/,"");return a},Ql:function(a){var b=[];a=c.querySelectorAll(a+
" input");for(var e=0;e<a.length;e++)a[e].checked&&b.push(a[e]);return b},FN:function(){var e="",d=c.querySelector(a.pb),h=c.documentElement,g=c.getElementsByTagName("body")[0],k=b.innerWidth||h.clientWidth||g.clientWidth;h=b.innerHeight||h.clientHeight||g.clientHeight;q.ld(d,"portrait");q.ld(d,"landscape");q.ld(d,"standard");k<h?e="portrait":675<=k?e="landscape":225<=k&&(e="standard");"portrait"===e&&360>h?e="basic-small portrait":"landscape"===e&&90>h?e="basic-small horizontal":"standard"===e&&
220>h&&(e="basic-small horizontal");-1<e.indexOf("portrait")?p("portrait","logo-vertical.png"):p("landscape","logo.png");q.de(d,e)},nN:function(){for(var b in f)f.hasOwnProperty(b)&&(a.Tc.hasOwnProperty(b)||(a.Tc[b]=f[b]))},mN:function(){var b=c.querySelector(a.ug);b.style.top=a.Tc.top;b.style.right=a.Tc.right;b.style.bottom=a.Tc.bottom;b.style.left=a.Tc.left}},r={TN:function(b){d.Rd=(b.target||b.srcElement).getAttribute("data-rate");for(b=0;b<m.length;b++)m[b].call(h,d.Rd);d.Rd<=a.Il?r.show(".aax-rating-feedback"):
r.show(".aax-rating-last")},vN:function(){for(var b=q.Ql(a.pb+" .aax-rating-feedback"),c=0;c<b.length;c++)d.reason[b[c].value]=1,b[c].checked=!1;for(b=0;b<g.length;b++)g[b].call(h,d.Rd,d.reason);r.show(".aax-rating-last")},kN:function(){if(!e&&null!==d.Rd){for(var b=q.Ql(a.pb+" .aax-rating-feedback"),c=0;c<b.length;c++)d.reason[b[c].value]=1,b[c].checked=!1;for(b=0;b<n.length;b++)n[b].call(h,d.Rd,d.reason)}},show:function(b){e=".aax-rating-last"===b;for(var d=c.querySelector(a.pb+" "+b),h=c.querySelector(".aax-popup"),
g=c.querySelectorAll(".show"),k=0;k<g.length;k++)g[k]!==h&&(q.ld(g[k],"show"),q.de(g[k],"hide"));-1<d.className.indexOf("hide")&&q.ld(d,"hide");q.de(d,"show");d=c.querySelector(a.pb+" .aax-optout");".aax-rating"===b?(q.ld(d,"hide"),q.de(d,"show")):(q.ld(d,"show"),q.de(d,"hide"))},Lx:function(){var b=c.querySelector(a.pb+".aax-popup");-1<b.className.indexOf("hide")&&q.ld(b,"hide");q.de(b,"show");e||r.Yw()},qv:function(){var b=c.querySelector(a.pb+".aax-popup");-1<b.className.indexOf("show")&&q.ld(b,
"show");q.de(b,"hide")},Yw:function(){r.show(".aax-rating");for(var b=q.Ql(a.pb+" .aax-rating-feedback"),c=0;c<b.length;c++)b[c].checked=!1;d.Rd=null;d.reason={}}},u=function(){for(var b=c.querySelectorAll(a.pb+" .star-list li"),e=0;e<b.length;e++)q.ri(b[e],"click",r.TN);q.ri(c.querySelector(a.pb+" .aax-rating-feedback .submit button"),"click",r.vN);q.ri(c.querySelector(a.ug),"click",r.Lx);q.ri(c.querySelector(a.pb+" .close-feedback"),"click",function(){r.kN();r.qv()})};h.init=function(){a.Tc&&q.nN();
for(var b in l)l.hasOwnProperty(b)&&"undefined"===typeof a[b]&&(a[b]=l[b]);for(var e in a)a.hasOwnProperty(e)&&(k[e]=a[e]);a.Tc&&q.mN();a.ux&&q.FN();if(null===c.querySelector(a.pb))throw"Container selector "+a.pb+" is not found/invalid";if(null===c.querySelector(a.ug))throw"CTA selector "+a.ug+" is not found/invalid";if(a.Oo||0===a.Oo)c.querySelector(a.pb).style.zIndex=a.Oo;if(a.Po||0===a.Po)c.querySelector(a.ug).style.zIndex=a.Po;u();return h};h.kt=function(){return d};h.CO=function(a){q.i(a)&&m.push(a)};
h.BO=function(a){q.i(a)&&g.push(a)};h.AO=function(a){q.i(a)&&n.push(a)};h.config=k;h.$w=r.Yw;h.gha={show:r.Lx,Wm:r.qv};return h}}});
__ad("postdata",["_","postdataconstants"],function(a,b){function c(){var b={},c=this;this.get=function(a){return b[a]};this.set=function(a,c){b[a]=c;return this};this.Z=function(){return a.extend({},b)};this.Qb=function(c){b=a.extend({},c);return this};this.id=function(b){a.a(b)&&c.set("pid",b);return c.get("pid")};this.Rb=function(b){a.a(b)&&c.set("pfid",b);return c.get("pfid")};this.target=function(b){a.a(b)&&c.set("ptarget",b);return c.get("ptarget")};this.source=function(b){if(a.a(b))c.set("psource",
b);else return c.get("psource")};c.set("pid",f++)}var f=1;c.F=b.F;return c});
__ad("ddagif","_ pqus inmemdatasource postmessagemanager postdata uhv qlf".split(" "),function(a,b,c,f,l,k,d){function m(a,d,h){d=!1;c.for(h).set("isAAX",!0);if("1"===c.for(h).get("sRdOut"))c.for(h).set("status",!0);else{var e=c.for(h).get("adCode");try{a.document.open(),a.document.write(e),a.document.close(),d=!0}catch(p){b.oa("Error while rendering the adcode"),d=!1}c.for(h).set("status",d)}}return{init:function(){a.a(window.aaxSettings.pmdelay)&&c.set("pmdelay",window.aaxSettings.pmdelay);f.init();
d.submit("//www.googletagservices.com/tag/js/gpt.js",{Y:["scr","plvf"],type:"script"});window.aax.deliverExchangeDemand=m}}});
__ad("displayframecore","_ pqus uhv postdata ie inmemdatasource srvwpf ddagif".split(" "),function(a,b,c,f,l,k,d,m){function g(){var a=(new f).set("phs",!0);a.target(k.get("tarOg"));a.Rb(k.get("fid"));window.top.postMessage(a.Z(),a.target())}function n(b){var c=window.document.createElement("div");c.id="aax_standard";a.Rc("@body:0",100,function(e){e.appendChild(c);a.i(b)&&b()})}b.Ih("AAX");window.aax=window.aax||{};(function(){var c=window.aax.__conf;try{if(a.a(window.name)){var e=JSON.parse(window.name);
a.extend(c,e)}}catch(p){b.oa("Failed to read window name")}a.c(c,function(a,b){k.set(b,a)})})();k.set("gdpr","1"===window.aaxSettings.gdpr);k.set("gdprconsent",window.aaxSettings.gdprconsent);k.set("uspst","1"===window.aaxSettings.uspst);k.set("uspcn","1"===window.aaxSettings.uspcn);k.set("icr","1"===window.aaxSettings.icr);a.X.V(window,"message",a.M(function(b){b.data&&b.origin===b.data.src&&b.data.id===a.Ya(k.get("fid"))&&("initRen"===b.data.type||"refReq"===b.data.type)&&a.triggerEvent("aaxOnMes",
"gbl",!0,b)}));return{start:function(){n(g);m.init();l.wr(window)}}});window.__ar(["displayframecore"],function(a){a.start()});
} catch (err) {
    window.aax.err = err;
    window.aax.errConsts = {"name":"aaxDisplayIframe","type":"AAX_DISPLAY_IFRAME","svr":"2021041511_109","servname":"c8-web-25","message":"aaxDisplayIframe encountered an error","path":"\/nerrping.php","customerId":"AAX763KC6","hostName":"https:\/\/l3.aaxads.com","get":{"userAgent":"userAgent","requrl":"requrl","cid":"cid","img":"img","d":"d"}};var Ta=window.aax.err,Ua=window.aax.errConsts;Ua=Ua||{};Ua.get=Ua.get||{};Ta=Ta||{};var Va={},Ya="",Za=encodeURIComponent(window.navigator.userAgent);Ya=Ta.stack?Ta.stack:Ta.s?Ta.s:Ta.stacktrace?Ta.stacktrace:"No StackTrace";var $a="",ab;for(ab in Ta)Ta.hasOwnProperty&&Ta.hasOwnProperty(ab)&&($a+=ab+" : '"+Ta[ab]+"',");Va.logLevel=3;Va.errorVal={};Va.errorVal.name=Ua.name;Va.errorVal.type=Ua.type;Va.errorVal.svr=Ua.svr;Va.errorVal.servname=Ua.servname;Va.errorVal.message=Ua.message;
Va.errorVal.stack=Ya;Va.errorVal.objTrace=$a;var bb="";bb="object"===typeof JSON&&"undefined"!==typeof JSON.stringify?JSON.stringify(Va):Va.errorVal.name+"@#@"+Va.errorVal.type+"@#@"+Ya+"@#@"+$a;bb=encodeURIComponent("["+bb+"]");var cb=Ua.hostName+Ua.path+"?"+Ua.get.userAgent+"="+Za+"&"+Ua.get.vha+"="+encodeURIComponent(window.location.href)+"&"+Ua.get.cid+"="+Ua.customerId+"&"+Ua.get.iga+"=logo.gif&"+Ua.get.d+"="+bb;(new Image).src=cb;
};